### PR TITLE
Some changes necessary to get things working on linux.

### PR DESCRIPTION
**Pull request by arichnad**
Let me know if I can clean these commits up any.

### CODE REVIEW

**Comment by danielr2e** [comment]
Arichnad - This is very much appreciated, and I will work on getting in merged into the master.  I'm a bit new to Git, but I'll figure it out eventually.

I apologize for the poor state of the code, things got hectic in the real world and I haven't been able to clean it up.  I expect to make some time for it later this week.

**Comment by arichnad** [comment]
Sounds good.

Instead, if you want to get your master back to compiling, I can re-submit my changes on your master.

That way you don't have to deal with the many merge conflicts.

**Comment by danielr2e** [comment]
That would be great, and much appreciated.

**Comment by arichnad** [comment]
Excellent.  I'll wait until the master worldwin-vr compiles again.

**Comment by danielr2e** [comment]
Arichnad - I took a few hours today to eliminate the silly build errors,
and also spruced up the build.xml and READMEs.

Just to clarify, once you have re-submitted your changes, I will still have
to merge them into the master myself, is that correct?

Again, thanks for your efforts, I'm excited to see this working on Linux.

**Comment by arichnad** [comment]
> Just to clarify, once you have re-submitted your changes, I will still have
> to merge them into the master myself, is that correct?

Yes, but it's really easy.  There won't be any conflicts (unless you
commit more), so you can use the UI to merge:  I think github has a
button that will do it.

Give me a sec to get things working again on your branch.

adrian

**Comment by arichnad** [comment]
Ok.  I've updated the pull request.  It should very easily merge into your stuff now.  I think github has a button you can click on to merge it in if you're happy with the changes.

**Comment by danielr2e** [comment]
Excellent - it looks like the github automerge isn't available, probably due to conflicts on the build.xml, which I also updated yesterday.  This weekend I'll do the merge locally, and maybe set up a linux box too so I can test that version from here on out.

**Comment by danielr2e** [comment]
Never mind, did not realize the button was on the conversation page.  That worked beautifully.  Thanks again.

**Pull request merged**
